### ISSUE TITLE
Update baseURI on the Product Comparator Demo website

### ISSUE THREAD

**Issue by Wendy-BA** [ConsumerDataStandardsAustralia/product-comparator-demo#218]
**Description**
As per below Zendesk article below, it appears I am able to request an update to the Product Comparator Demo website update via this issue repository. 
https://cdr-support.zendesk.com/hc/en-us/articles/900002933263-Add-your-organisation-to-the-Banking-Product-Comparator
Please could I request our baseURI on the Product Comparator Demo website to be updated to https://public.cdr-api.bankaust.com.au/ ?

many thanks
Wendy

**Comment by vadkor** [comment]
Hi @Wendy-BA. Sure, we can create the PR for you if you don't know how. In the meantime, could you please email us on [contact@consumerdatastandards.gov.au](mailto:contact@consumerdatastandards.gov.au) so we can verify your association with Bank Australia.

**Comment by Wendy-BA** [comment]
Hi Vadkor, thank you for updating the Bank Australia URL in October. It has been brought to our attention that the below github location also requires updating
https://github.com/LukePrior/Australian-Open-Banking-Data-Database#list-of-current-providers---113

Please could you advise how this list can be updated for Bank Australia?

The URL should be updated to : https://public.cdr-api.bankaust.com.au/cds-au/v1

many thanks
Wendy

**Comment by vadkor** [comment]
Hi Wendy. The list of the Open Banking data sources you are referring to is being maintained by a private entity, not affiliated with Data Standards Body / ConsumerDataStandardsAustralia. I would recommend contacting @LukePrior or raising an issue or a PR in that GitHub repository.

**Comment by LukePrior** [comment]
Hi @Wendy-BA 

I've taken this opportunity to move the Australian Open Banking Data Database repository to using the Data Holder Brands Summary [API](https://www.cdr.gov.au/for-providers/how-find-data-holders-product-data-request-service) so that all sources stay correct.

The repository was created before the official API was published to serve as a central source of all URLs but it is still quite popular so it's good to keep it up to date.

Thanks,
Luke
